
DROP sequence "SEQ_TEST";

CREATE SEQUENCE SEQ_TEST
			INCREMENT BY 1
			START WITH 1
			NOCYCLE;
            

-- 실험용 유저 비밀번호는 모두 'test' 암호화 시킨것으로 통일
BEGIN 
    FOR I IN 1..110
    LOOP 
    -- 실험용 유저 데이터 추가 
        INSERT INTO MEMBER(USER_ID, USER_PWD, NICKNAME)
		VALUES( 't'||SEQ_TEST.NEXTVAL , '7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==', 'NIC'||SEQ_TEST.CURRVAL);
        
        INSERT INTO LOGIN_API(USER_ID, API_KIND, API_KEY)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'kakao', '가상의kakao키');
        
        INSERT INTO CHARACTER(USER_ID, SKIN_ID)
		VALUES( 't'||SEQ_TEST.CURRVAL , 0);
        
        INSERT INTO MEMBER(USER_ID, USER_PWD, NICKNAME)
		VALUES( 't'||SEQ_TEST.NEXTVAL , '7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==', 'NIC'||SEQ_TEST.CURRVAL);
        
        INSERT INTO LOGIN_API(USER_ID, API_KIND, API_KEY)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'google', '가상의google키');
        
        INSERT INTO CHARACTER(USER_ID, SKIN_ID)
		VALUES( 't'||SEQ_TEST.CURRVAL , 0);
    END LOOP;
END;
/



BEGIN 
    FOR I IN 1..22
    LOOP 
    -- 실험용 유저 데이터 추가 
        INSERT INTO MEMBER(USER_ID, USER_PWD, NICKNAME)
		VALUES( 't'||SEQ_TEST.NEXTVAL , '7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==', 'NIC'||SEQ_TEST.CURRVAL);
        
        INSERT INTO LOGIN_API(USER_ID, API_KIND, API_KEY)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'kakao', '가상의kakao키');
        
        INSERT INTO CHARACTER(USER_ID, SKIN_ID)
		VALUES( 't'||SEQ_TEST.CURRVAL , 0);
        
        
        INSERT INTO CHATTINGROOM(USER_ID, RECEIVE_ID)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'test');
        
        INSERT INTO CHATTINGROOM(RECEIVE_ID, USER_ID)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'test');

    END LOOP;
END;
/


BEGIN 
    FOR I IN 1..50
    LOOP 
    -- 실험용 유저 데이터 추가 
        INSERT INTO MEMBER(USER_ID, USER_PWD, NICKNAME, STATUS)
		VALUES( 't'||SEQ_TEST.NEXTVAL , '7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==', 'NIC'||SEQ_TEST.CURRVAL, 'N');
        
        INSERT INTO LOGIN_API(USER_ID, API_KIND, API_KEY)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'kakao', '가상의kakao키');
        
        INSERT INTO CHARACTER(USER_ID, SKIN_ID)
		VALUES( 't'||SEQ_TEST.CURRVAL , 0);
        
        INSERT INTO DISABLED_MEMBER(USER_ID, STATUS, CANCELLATION_DATE)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'N', SYSDATE - 15);
        
        INSERT INTO MEMBER(USER_ID, USER_PWD, NICKNAME, STATUS)
		VALUES( 't'||SEQ_TEST.NEXTVAL , '7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==', 'NIC'||SEQ_TEST.CURRVAL, 'X');
        
        INSERT INTO LOGIN_API(USER_ID, API_KIND, API_KEY)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'google', '가상의google키');
        
        INSERT INTO CHARACTER(USER_ID, SKIN_ID)
		VALUES( 't'||SEQ_TEST.CURRVAL , 0);
        
        INSERT INTO DISABLED_MEMBER(USER_ID, STATUS, CANCELLATION_DATE)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'X', SYSDATE - 15);
    END LOOP;
END;
/


DROP sequence "SEQ_TEST";

CREATE SEQUENCE SEQ_TEST
			INCREMENT BY 1
			START WITH 3
			NOCYCLE;

BEGIN 
    FOR I IN 1..10
    LOOP 
    -- 실험용 유저 데이터 추가 
        INSERT INTO HEART(USER_ID, RECEIVE_ID, CREATE_DATE)
		VALUES( 't'||SEQ_TEST.NEXTVAL , 'test', SYSDATE);
        
        INSERT INTO HEART(USER_ID, RECEIVE_ID, CREATE_DATE)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'test', SYSDATE-7);
    END LOOP;
END;
/

BEGIN 
    FOR I IN 1..20
    LOOP 
    -- 실험용 유저 데이터 추가 
        INSERT INTO HEART(USER_ID, RECEIVE_ID, CREATE_DATE)
		VALUES( 't'||SEQ_TEST.NEXTVAL , 'friend', SYSDATE);
        
        INSERT INTO HEART(USER_ID, RECEIVE_ID, CREATE_DATE)
		VALUES( 't'||SEQ_TEST.CURRVAL , 'friend', SYSDATE-7);
    END LOOP;
END;
/




COMMIT;
